#!/usr/bin/env bash
# scripts/server/install_orb_firewall.sh - only the TOWER (LAN + Tailscale) and this machine may
# reach my app port (5876) on the server: the app on the tower streams my camera + chats with me
# through it once I live here. Addresses come from config/private.local.json (never the repo).
# Installs a root systemd unit that re-applies the rules at every boot. Needs sudo. (2026-10-07)
set -eu
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
read -r LAN TS < <(python3 -c 'import json,sys;d=json.load(open(sys.argv[1]));print(d.get("tower_lan",""), d.get("tower_tailnet",""))' "$ROOT/config/private.local.json")
[ -n "$LAN" ] && [ -n "$TS" ] || { echo "tower_lan / tower_tailnet missing from private config"; exit 3; }
RULES=/usr/local/sbin/iris-orb-firewall.sh
sudo tee "$RULES" >/dev/null <<RULES_EOF
#!/bin/sh
# generated by install_orb_firewall.sh - port 5876: tower + localhost only
iptables -N IRIS_ORB 2>/dev/null || iptables -F IRIS_ORB
iptables -A IRIS_ORB -s 127.0.0.1 -j ACCEPT
iptables -A IRIS_ORB -s $LAN -j ACCEPT
iptables -A IRIS_ORB -s $TS -j ACCEPT
iptables -A IRIS_ORB -j DROP
iptables -C INPUT -p tcp --dport 5876 -j IRIS_ORB 2>/dev/null || iptables -I INPUT -p tcp --dport 5876 -j IRIS_ORB
RULES_EOF
sudo chmod 700 "$RULES"
sudo tee /etc/systemd/system/iris-orb-firewall.service >/dev/null <<'UNIT_EOF'
[Unit]
Description=Iris app port 5876: tower + localhost only
After=network-online.target tailscaled.service
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/local/sbin/iris-orb-firewall.sh

[Install]
WantedBy=multi-user.target
UNIT_EOF
sudo systemctl daemon-reload
sudo systemctl enable --now iris-orb-firewall.service
sudo iptables -S IRIS_ORB | sed -E 's/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/x.x.x.x/g'
